/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

export type EnrollmentAccessGroupPreview = {
    /**
     * Autogenerated ID
     */
    readonly id?: string;
    /**
     * LDAP Group ID
     */
    groupId: string;
    ldapServerId: string;
    name: string;
    siteId?: string;
    enterpriseEnrollmentEnabled?: boolean;
    personalEnrollmentEnabled?: boolean;
    accountDrivenUserEnrollmentEnabled?: boolean;
    requireEula?: boolean;
};

