/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
export { ApiError } from './core/ApiError.ts';
export { CancelablePromise, CancelError } from './core/CancelablePromise.ts';
export { OpenAPI } from './core/OpenAPI.ts';
export type { OpenAPIConfig } from './core/OpenAPI.ts';

export type { AccessGroupsPreviewSearchResults } from './models/AccessGroupsPreviewSearchResults.ts';
export type { AccessGroupsV2SearchResults } from './models/AccessGroupsV2SearchResults.ts';
export type { Account } from './models/Account.ts';
export type { AccountDrivenUserEnrollmentSessionTokenSettings } from './models/AccountDrivenUserEnrollmentSessionTokenSettings.ts';
export type { AccountGroup } from './models/AccountGroup.ts';
export type { AccountPreferences } from './models/AccountPreferences.ts';
export type { AccountPreferencesV1 } from './models/AccountPreferencesV1.ts';
export type { AccountPreferencesV4 } from './models/AccountPreferencesV4.ts';
export type { ActivePatchHistory } from './models/ActivePatchHistory.ts';
export type { ActivePatchHistorySearchResults } from './models/ActivePatchHistorySearchResults.ts';
export type { ActivePatchSummary } from './models/ActivePatchSummary.ts';
export type { AdminAccount } from './models/AdminAccount.ts';
export type { AdvancedSearch } from './models/AdvancedSearch.ts';
export type { AdvancedSearchCriteriaChoices } from './models/AdvancedSearchCriteriaChoices.ts';
export type { AdvancedSearchSearchResults } from './models/AdvancedSearchSearchResults.ts';
export type { AdvancedUserContentSearch } from './models/AdvancedUserContentSearch.ts';
export type { AdvancedUserContentSearchSearchResults } from './models/AdvancedUserContentSearchSearchResults.ts';
export type { AndroidDetails } from './models/AndroidDetails.ts';
export type { ApiError } from './models/ApiError.ts';
export type { ApiErrorCause } from './models/ApiErrorCause.ts';
export type { AppAnalyticsSetting } from './models/AppAnalyticsSetting.ts';
export type { AppDynamicsConfig } from './models/AppDynamicsConfig.ts';
export type { AppleTvDetails } from './models/AppleTvDetails.ts';
export type { ApplicationAttributes } from './models/ApplicationAttributes.ts';
export type { ApplicationConfiguration } from './models/ApplicationConfiguration.ts';
export type { AppPath } from './models/AppPath.ts';
export type { AppRequestFormInputField } from './models/AppRequestFormInputField.ts';
export type { AppRequestFormInputFieldSearchResults } from './models/AppRequestFormInputFieldSearchResults.ts';
export type { AppRequestSettings } from './models/AppRequestSettings.ts';
export type { AssignRemoveProfileResponseSyncState } from './models/AssignRemoveProfileResponseSyncState.ts';
export type { Attributes } from './models/Attributes.ts';
export type { AuthAccount } from './models/AuthAccount.ts';
export type { AuthAccountV1 } from './models/AuthAccountV1.ts';
export type { Authorization } from './models/Authorization.ts';
export type { AuthorizationV1 } from './models/AuthorizationV1.ts';
export type { AuthToken } from './models/AuthToken.ts';
export type { AuthTokenV1 } from './models/AuthTokenV1.ts';
export type { AvailableUpdates } from './models/AvailableUpdates.ts';
export type { AzureAdMigrationReportProcessStatus } from './models/AzureAdMigrationReportProcessStatus.ts';
export type { AzureAdMigrationReportRequest } from './models/AzureAdMigrationReportRequest.ts';
export type { AzureConfiguration } from './models/AzureConfiguration.ts';
export type { AzureConfigurationRequest } from './models/AzureConfigurationRequest.ts';
export type { AzureConfigurationUpdate } from './models/AzureConfigurationUpdate.ts';
export type { AzureMappings } from './models/AzureMappings.ts';
export type { AzureServerConfiguration } from './models/AzureServerConfiguration.ts';
export type { AzureServerConfigurationRequest } from './models/AzureServerConfigurationRequest.ts';
export type { AzureServerConfigurationUpdate } from './models/AzureServerConfigurationUpdate.ts';
export type { BrandingImageUrl } from './models/BrandingImageUrl.ts';
export type { Building } from './models/Building.ts';
export type { BuildingSearchResults } from './models/BuildingSearchResults.ts';
export type { CacheSettings } from './models/CacheSettings.ts';
export type { CategoriesSearchResults } from './models/CategoriesSearchResults.ts';
export type { Category } from './models/Category.ts';
export type { CertificateDetails } from './models/CertificateDetails.ts';
export type { CertificateIdentityV2 } from './models/CertificateIdentityV2.ts';
export type { CertificateKey } from './models/CertificateKey.ts';
export type { CertificateRecord } from './models/CertificateRecord.ts';
export type { ClassicLdapMappings } from './models/ClassicLdapMappings.ts';
export type { ClientCheckInV2 } from './models/ClientCheckInV2.ts';
export type { ClientCheckInV3 } from './models/ClientCheckInV3.ts';
export type { CloudIdPCommon } from './models/CloudIdPCommon.ts';
export type { CloudIdPCommonRequest } from './models/CloudIdPCommonRequest.ts';
export type { CloudIdPCommonResponse } from './models/CloudIdPCommonResponse.ts';
export type { CloudLdapConnectionPoolStatistics } from './models/CloudLdapConnectionPoolStatistics.ts';
export type { CloudLdapConnectionStatus } from './models/CloudLdapConnectionStatus.ts';
export type { CloudLdapKeystore } from './models/CloudLdapKeystore.ts';
export type { CloudLdapKeystoreFile } from './models/CloudLdapKeystoreFile.ts';
export type { CloudLdapMappingsRequest } from './models/CloudLdapMappingsRequest.ts';
export type { CloudLdapMappingsResponse } from './models/CloudLdapMappingsResponse.ts';
export type { CloudLdapServerRequest } from './models/CloudLdapServerRequest.ts';
export type { CloudLdapServerResponse } from './models/CloudLdapServerResponse.ts';
export type { CloudLdapServerUpdate } from './models/CloudLdapServerUpdate.ts';
export type { ComplianceVendorDeviceInformation } from './models/ComplianceVendorDeviceInformation.ts';
export type { ComputerApplication } from './models/ComputerApplication.ts';
export type { ComputerAttachment } from './models/ComputerAttachment.ts';
export type { ComputerCertificate } from './models/ComputerCertificate.ts';
export type { ComputerConfigurationProfile } from './models/ComputerConfigurationProfile.ts';
export type { ComputerContentCaching } from './models/ComputerContentCaching.ts';
export type { ComputerContentCachingAlert } from './models/ComputerContentCachingAlert.ts';
export type { ComputerContentCachingCacheDetail } from './models/ComputerContentCachingCacheDetail.ts';
export type { ComputerContentCachingDataMigrationError } from './models/ComputerContentCachingDataMigrationError.ts';
export type { ComputerContentCachingDataMigrationErrorUserInfo } from './models/ComputerContentCachingDataMigrationErrorUserInfo.ts';
export type { ComputerContentCachingParent } from './models/ComputerContentCachingParent.ts';
export type { ComputerContentCachingParentAlert } from './models/ComputerContentCachingParentAlert.ts';
export type { ComputerContentCachingParentCapabilities } from './models/ComputerContentCachingParentCapabilities.ts';
export type { ComputerContentCachingParentDetails } from './models/ComputerContentCachingParentDetails.ts';
export type { ComputerContentCachingParentLocalNetwork } from './models/ComputerContentCachingParentLocalNetwork.ts';
export type { ComputerDisk } from './models/ComputerDisk.ts';
export type { ComputerDiskEncryption } from './models/ComputerDiskEncryption.ts';
export type { ComputerExtensionAttribute } from './models/ComputerExtensionAttribute.ts';
export type { ComputerFont } from './models/ComputerFont.ts';
export type { ComputerGeneral } from './models/ComputerGeneral.ts';
export type { ComputerGeneralUpdate } from './models/ComputerGeneralUpdate.ts';
export type { ComputerGroup } from './models/ComputerGroup.ts';
export type { ComputerHardware } from './models/ComputerHardware.ts';
export type { ComputerHardwareUpdate } from './models/ComputerHardwareUpdate.ts';
export type { ComputerIbeacon } from './models/ComputerIbeacon.ts';
export type { ComputerInventory } from './models/ComputerInventory.ts';
export type { ComputerInventoryCollectionPreferences } from './models/ComputerInventoryCollectionPreferences.ts';
export type { ComputerInventoryCollectionSettings } from './models/ComputerInventoryCollectionSettings.ts';
export type { ComputerInventoryRecoveryLockPasswordResponse } from './models/ComputerInventoryRecoveryLockPasswordResponse.ts';
export type { ComputerInventorySearchResults } from './models/ComputerInventorySearchResults.ts';
export type { ComputerInventoryUpdateRequest } from './models/ComputerInventoryUpdateRequest.ts';
export type { ComputerLicensedSoftware } from './models/ComputerLicensedSoftware.ts';
export type { ComputerLocalUserAccount } from './models/ComputerLocalUserAccount.ts';
export type { ComputerLocation } from './models/ComputerLocation.ts';
export type { ComputerMdmCapability } from './models/ComputerMdmCapability.ts';
export type { ComputerOperatingSystem } from './models/ComputerOperatingSystem.ts';
export type { ComputerOperatingSystemUpdate } from './models/ComputerOperatingSystemUpdate.ts';
export type { ComputerOverview } from './models/ComputerOverview.ts';
export type { ComputerPackageReceipts } from './models/ComputerPackageReceipts.ts';
export type { ComputerPartition } from './models/ComputerPartition.ts';
export type { ComputerPartitionEncryption } from './models/ComputerPartitionEncryption.ts';
export type { ComputerPartitionFileVault2State } from './models/ComputerPartitionFileVault2State.ts';
export type { ComputerPlugin } from './models/ComputerPlugin.ts';
export type { ComputerPrestage } from './models/ComputerPrestage.ts';
export type { ComputerPrestageSearchResults } from './models/ComputerPrestageSearchResults.ts';
export type { ComputerPrestageSearchResultsV2 } from './models/ComputerPrestageSearchResultsV2.ts';
export type { ComputerPrestageV2 } from './models/ComputerPrestageV2.ts';
export type { ComputerPrinter } from './models/ComputerPrinter.ts';
export type { ComputerPurchase } from './models/ComputerPurchase.ts';
export type { ComputerRemoteManagement } from './models/ComputerRemoteManagement.ts';
export type { ComputerSection } from './models/ComputerSection.ts';
export type { ComputerSecurity } from './models/ComputerSecurity.ts';
export type { ComputerService } from './models/ComputerService.ts';
export type { ComputerSoftwareUpdate } from './models/ComputerSoftwareUpdate.ts';
export type { ComputersSearchResults } from './models/ComputersSearchResults.ts';
export type { ComputerStorage } from './models/ComputerStorage.ts';
export type { ComputerUserAndLocation } from './models/ComputerUserAndLocation.ts';
export type { ConfigurationProfile } from './models/ConfigurationProfile.ts';
export type { ConfigurationSearchResults } from './models/ConfigurationSearchResults.ts';
export type { ConnectionConfigurationCandidateRequest } from './models/ConnectionConfigurationCandidateRequest.ts';
export type { ConnectionConfigurationResponse } from './models/ConnectionConfigurationResponse.ts';
export type { ConnectionConfigurationStatusResponse } from './models/ConnectionConfigurationStatusResponse.ts';
export type { ConnectionConfigurationUpdateRequest } from './models/ConnectionConfigurationUpdateRequest.ts';
export type { Country } from './models/Country.ts';
export type { CountryCodes } from './models/CountryCodes.ts';
export type { CreatePath } from './models/CreatePath.ts';
export type { CsaToken } from './models/CsaToken.ts';
export type { CurrentAccount } from './models/CurrentAccount.ts';
export type { CurrentAuthorization } from './models/CurrentAuthorization.ts';
export type { DatabasePassword } from './models/DatabasePassword.ts';
export type { DataRoamingSetting } from './models/DataRoamingSetting.ts';
export type { DayOfWeek } from './models/DayOfWeek.ts';
export type { DeclarativeManagementCommand } from './models/DeclarativeManagementCommand.ts';
export type { DeleteUserCommand } from './models/DeleteUserCommand.ts';
export type { Department } from './models/Department.ts';
export type { DepartmentsSearchResults } from './models/DepartmentsSearchResults.ts';
export type { DeploymentTask } from './models/DeploymentTask.ts';
export type { DeploymentTaskSearchResults } from './models/DeploymentTaskSearchResults.ts';
export type { DeviceCommunicationSettings } from './models/DeviceCommunicationSettings.ts';
export type { DeviceComplianceInformation } from './models/DeviceComplianceInformation.ts';
export type { DeviceEnrollmentDevice } from './models/DeviceEnrollmentDevice.ts';
export type { DeviceEnrollmentDeviceSearchResults } from './models/DeviceEnrollmentDeviceSearchResults.ts';
export type { DeviceEnrollmentDisownBody } from './models/DeviceEnrollmentDisownBody.ts';
export type { DeviceEnrollmentDisownResponse } from './models/DeviceEnrollmentDisownResponse.ts';
export type { DeviceEnrollmentInstance } from './models/DeviceEnrollmentInstance.ts';
export type { DeviceEnrollmentInstanceSearchResults } from './models/DeviceEnrollmentInstanceSearchResults.ts';
export type { DeviceEnrollmentInstanceSyncStatus } from './models/DeviceEnrollmentInstanceSyncStatus.ts';
export type { DeviceEnrollmentPrestage } from './models/DeviceEnrollmentPrestage.ts';
export type { DeviceEnrollmentPrestageV2 } from './models/DeviceEnrollmentPrestageV2.ts';
export type { DeviceEnrollmentToken } from './models/DeviceEnrollmentToken.ts';
export type { DiagnosticSubmissionSetting } from './models/DiagnosticSubmissionSetting.ts';
export type { Ebook } from './models/Ebook.ts';
export type { EbookExclusions } from './models/EbookExclusions.ts';
export type { EbookLimitations } from './models/EbookLimitations.ts';
export type { EbookScope } from './models/EbookScope.ts';
export type { EbookSearchResults } from './models/EbookSearchResults.ts';
export type { EnableLostModeCommand } from './models/EnableLostModeCommand.ts';
export type { Engage } from './models/Engage.ts';
export type { EnrollmentAccessGroupPreview } from './models/EnrollmentAccessGroupPreview.ts';
export type { EnrollmentAccessGroupV2 } from './models/EnrollmentAccessGroupV2.ts';
export type { EnrollmentCustomization } from './models/EnrollmentCustomization.ts';
export type { EnrollmentCustomizationBrandingSettings } from './models/EnrollmentCustomizationBrandingSettings.ts';
export type { EnrollmentCustomizationDependencies } from './models/EnrollmentCustomizationDependencies.ts';
export type { EnrollmentCustomizationDependency } from './models/EnrollmentCustomizationDependency.ts';
export type { EnrollmentCustomizationLdapGroupAccess } from './models/EnrollmentCustomizationLdapGroupAccess.ts';
export type { EnrollmentCustomizationPanel } from './models/EnrollmentCustomizationPanel.ts';
export type { EnrollmentCustomizationPanelLdapAuth } from './models/EnrollmentCustomizationPanelLdapAuth.ts';
export type { EnrollmentCustomizationPanelList } from './models/EnrollmentCustomizationPanelList.ts';
export type { EnrollmentCustomizationPanelSsoAuth } from './models/EnrollmentCustomizationPanelSsoAuth.ts';
export type { EnrollmentCustomizationPanelText } from './models/EnrollmentCustomizationPanelText.ts';
export type { EnrollmentCustomizationSearchResults } from './models/EnrollmentCustomizationSearchResults.ts';
export type { EnrollmentCustomizationSearchResultsV2 } from './models/EnrollmentCustomizationSearchResultsV2.ts';
export type { EnrollmentCustomizationV2 } from './models/EnrollmentCustomizationV2.ts';
export type { EnrollmentMethod } from './models/EnrollmentMethod.ts';
export type { EnrollmentProcessTextObject } from './models/EnrollmentProcessTextObject.ts';
export type { EnrollmentSettingsV2 } from './models/EnrollmentSettingsV2.ts';
export type { ExportField } from './models/ExportField.ts';
export type { ExportParameters } from './models/ExportParameters.ts';
export type { ExtensionAttribute } from './models/ExtensionAttribute.ts';
export type { ExtensionAttributeMigrationMappingChange } from './models/ExtensionAttributeMigrationMappingChange.ts';
export type { ExtensionAttributeV2 } from './models/ExtensionAttributeV2.ts';
export type { ExternalRecipient } from './models/ExternalRecipient.ts';
export type { FileAttachment } from './models/FileAttachment.ts';
export type { FileAttachmentDelete } from './models/FileAttachmentDelete.ts';
export type { FileAttachmentV2 } from './models/FileAttachmentV2.ts';
export type { Filter } from './models/Filter.ts';
export type { FontPath } from './models/FontPath.ts';
export type { GetComputerPrestage } from './models/GetComputerPrestage.ts';
export type { GetComputerPrestageV2 } from './models/GetComputerPrestageV2.ts';
export type { GetEnrollmentCustomization } from './models/GetEnrollmentCustomization.ts';
export type { GetEnrollmentCustomizationPanel } from './models/GetEnrollmentCustomizationPanel.ts';
export type { GetEnrollmentCustomizationPanelLdapAuth } from './models/GetEnrollmentCustomizationPanelLdapAuth.ts';
export type { GetEnrollmentCustomizationPanelSsoAuth } from './models/GetEnrollmentCustomizationPanelSsoAuth.ts';
export type { GetEnrollmentCustomizationPanelText } from './models/GetEnrollmentCustomizationPanelText.ts';
export type { GetMobileDevicePrestage } from './models/GetMobileDevicePrestage.ts';
export type { GetMobileDevicePrestageV2 } from './models/GetMobileDevicePrestageV2.ts';
export type { GroupMappings } from './models/GroupMappings.ts';
export type { GroupMembership } from './models/GroupMembership.ts';
export type { GroupTestSearch } from './models/GroupTestSearch.ts';
export type { GroupTestSearchRequest } from './models/GroupTestSearchRequest.ts';
export type { GroupTestSearchResponse } from './models/GroupTestSearchResponse.ts';
export type { HistorySearchResults } from './models/HistorySearchResults.ts';
export type { HistorySearchResultsV1 } from './models/HistorySearchResultsV1.ts';
export type { HrefResponse } from './models/HrefResponse.ts';
export type { IconResponse } from './models/IconResponse.ts';
export type { IdAndName } from './models/IdAndName.ts';
export type { IdAndNameV2 } from './models/IdAndNameV2.ts';
export type { Ids } from './models/Ids.ts';
export type { Initialize } from './models/Initialize.ts';
export type { InitializeV1 } from './models/InitializeV1.ts';
export type { InstallPackage } from './models/InstallPackage.ts';
export type { IntegerWrapper } from './models/IntegerWrapper.ts';
export type { InternalRecipient } from './models/InternalRecipient.ts';
export type { InventoryInformation } from './models/InventoryInformation.ts';
export type { InventoryPreloadCsvError } from './models/InventoryPreloadCsvError.ts';
export type { InventoryPreloadCsvValidationError } from './models/InventoryPreloadCsvValidationError.ts';
export type { InventoryPreloadCsvValidationErrorCause } from './models/InventoryPreloadCsvValidationErrorCause.ts';
export type { InventoryPreloadCsvValidationSuccess } from './models/InventoryPreloadCsvValidationSuccess.ts';
export type { InventoryPreloadExtensionAttribute } from './models/InventoryPreloadExtensionAttribute.ts';
export type { InventoryPreloadExtensionAttributeColumn } from './models/InventoryPreloadExtensionAttributeColumn.ts';
export type { InventoryPreloadExtensionAttributeColumnResult } from './models/InventoryPreloadExtensionAttributeColumnResult.ts';
export type { InventoryPreloadInvalidCsvResponse } from './models/InventoryPreloadInvalidCsvResponse.ts';
export type { InventoryPreloadRecord } from './models/InventoryPreloadRecord.ts';
export type { InventoryPreloadRecordSearchResults } from './models/InventoryPreloadRecordSearchResults.ts';
export type { InventoryPreloadRecordSearchResultsV2 } from './models/InventoryPreloadRecordSearchResultsV2.ts';
export type { InventoryPreloadRecordV2 } from './models/InventoryPreloadRecordV2.ts';
export type { IosBrandingConfiguration } from './models/IosBrandingConfiguration.ts';
export type { IosBrandingSearchResults } from './models/IosBrandingSearchResults.ts';
export type { IosDetails } from './models/IosDetails.ts';
export type { IosDetailsV2 } from './models/IosDetailsV2.ts';
export type { JamfApplicationResponse } from './models/JamfApplicationResponse.ts';
export type { JamfNationCredentials } from './models/JamfNationCredentials.ts';
export type { JamfPackageResponse } from './models/JamfPackageResponse.ts';
export type { JamfProInformation } from './models/JamfProInformation.ts';
export type { JamfProInformationV2 } from './models/JamfProInformationV2.ts';
export type { JamfProServerUrl } from './models/JamfProServerUrl.ts';
export type { JamfProtectPlan } from './models/JamfProtectPlan.ts';
export type { JamfProVersion } from './models/JamfProVersion.ts';
export type { LanguageCode } from './models/LanguageCode.ts';
export type { LdapConfigurationRequest } from './models/LdapConfigurationRequest.ts';
export type { LdapConfigurationResponse } from './models/LdapConfigurationResponse.ts';
export type { LdapConfigurationUpdate } from './models/LdapConfigurationUpdate.ts';
export type { LdapGroup } from './models/LdapGroup.ts';
export type { LdapGroupSearchResults } from './models/LdapGroupSearchResults.ts';
export type { LdapServer } from './models/LdapServer.ts';
export type { LinkedConnectProfile } from './models/LinkedConnectProfile.ts';
export type { LinkedConnectProfileSearchResults } from './models/LinkedConnectProfileSearchResults.ts';
export type { Locale } from './models/Locale.ts';
export type { Location } from './models/Location.ts';
export type { LocationInformation } from './models/LocationInformation.ts';
export type { LocationInformationV2 } from './models/LocationInformationV2.ts';
export type { LocationV2 } from './models/LocationV2.ts';
export type { LogOutUserCommand } from './models/LogOutUserCommand.ts';
export type { MacOsBrandingConfiguration } from './models/MacOsBrandingConfiguration.ts';
export type { MacOsBrandingSearchResults } from './models/MacOsBrandingSearchResults.ts';
export type { MacOsManagedSoftwareUpdate } from './models/MacOsManagedSoftwareUpdate.ts';
export type { MacOsManagedSoftwareUpdateResponse } from './models/MacOsManagedSoftwareUpdateResponse.ts';
export type { Markdown } from './models/Markdown.ts';
export type { MdmClientType } from './models/MdmClientType.ts';
export type { MdmCommand } from './models/MdmCommand.ts';
export type { MdmCommandClient } from './models/MdmCommandClient.ts';
export type { MdmCommandClientRequest } from './models/MdmCommandClientRequest.ts';
export type { MdmCommandRequest } from './models/MdmCommandRequest.ts';
export type { MdmCommandResults } from './models/MdmCommandResults.ts';
export type { MdmCommandState } from './models/MdmCommandState.ts';
export type { MdmCommandType } from './models/MdmCommandType.ts';
export type { MembershipMappings } from './models/MembershipMappings.ts';
export type { MembershipTestSearchRequest } from './models/MembershipTestSearchRequest.ts';
export type { MembershipTestSearchResponse } from './models/MembershipTestSearchResponse.ts';
export type { MemcachedEndpoints } from './models/MemcachedEndpoints.ts';
export type { MobileDevice } from './models/MobileDevice.ts';
export type { MobileDeviceApplication } from './models/MobileDeviceApplication.ts';
export type { MobileDeviceAttachment } from './models/MobileDeviceAttachment.ts';
export type { MobileDeviceAttachmentV2 } from './models/MobileDeviceAttachmentV2.ts';
export type { MobileDeviceCertificateV1 } from './models/MobileDeviceCertificateV1.ts';
export type { MobileDeviceCertificateV2 } from './models/MobileDeviceCertificateV2.ts';
export type { MobileDeviceDetails } from './models/MobileDeviceDetails.ts';
export type { MobileDeviceDetailsGetV2 } from './models/MobileDeviceDetailsGetV2.ts';
export type { MobileDeviceDetailsV2 } from './models/MobileDeviceDetailsV2.ts';
export type { MobileDeviceEbook } from './models/MobileDeviceEbook.ts';
export type { MobileDeviceExtensionAttributeResults } from './models/MobileDeviceExtensionAttributeResults.ts';
export type { MobileDeviceGroup } from './models/MobileDeviceGroup.ts';
export type { MobileDevicePrestage } from './models/MobileDevicePrestage.ts';
export type { MobileDevicePrestageName } from './models/MobileDevicePrestageName.ts';
export type { MobileDevicePrestageNames } from './models/MobileDevicePrestageNames.ts';
export type { MobileDevicePrestageNamesV2 } from './models/MobileDevicePrestageNamesV2.ts';
export type { MobileDevicePrestageNameV2 } from './models/MobileDevicePrestageNameV2.ts';
export type { MobileDevicePrestageSearchResults } from './models/MobileDevicePrestageSearchResults.ts';
export type { MobileDevicePrestageSearchResultsV2 } from './models/MobileDevicePrestageSearchResultsV2.ts';
export type { MobileDevicePrestageV2 } from './models/MobileDevicePrestageV2.ts';
export type { MobileDeviceSearchParams } from './models/MobileDeviceSearchParams.ts';
export type { MobileDeviceSearchResults } from './models/MobileDeviceSearchResults.ts';
export type { MobileDeviceSearchResultsV2 } from './models/MobileDeviceSearchResultsV2.ts';
export type { MobileDeviceServiceSubscription } from './models/MobileDeviceServiceSubscription.ts';
export type { MobileDeviceV2 } from './models/MobileDeviceV2.ts';
export type { Network } from './models/Network.ts';
export type { NetworkV2 } from './models/NetworkV2.ts';
export type { Notification } from './models/Notification.ts';
export type { NotificationType } from './models/NotificationType.ts';
export type { NotificationV1 } from './models/NotificationV1.ts';
export type { ObjectHistory } from './models/ObjectHistory.ts';
export type { ObjectHistoryNote } from './models/ObjectHistoryNote.ts';
export type { ObjectHistoryV1 } from './models/ObjectHistoryV1.ts';
export type { OrderBy } from './models/OrderBy.ts';
export type { PackageManifest } from './models/PackageManifest.ts';
export type { ParentApp } from './models/ParentApp.ts';
export type { PatchIdsOnDashboard } from './models/PatchIdsOnDashboard.ts';
export type { PatchPolicyAttempt } from './models/PatchPolicyAttempt.ts';
export type { PatchPolicyAttemptAction } from './models/PatchPolicyAttemptAction.ts';
export type { PatchPolicyLog } from './models/PatchPolicyLog.ts';
export type { PatchPolicyLogSearchResults } from './models/PatchPolicyLogSearchResults.ts';
export type { PatchPolicyOnDashboard } from './models/PatchPolicyOnDashboard.ts';
export type { PatchPolicySummary } from './models/PatchPolicySummary.ts';
export type { PatchVersion } from './models/PatchVersion.ts';
export type { PersonalHotspotSetting } from './models/PersonalHotspotSetting.ts';
export type { PlanSearchResults } from './models/PlanSearchResults.ts';
export type { PluginPath } from './models/PluginPath.ts';
export type { PolicyProperties } from './models/PolicyProperties.ts';
export type { PolicyPropertiesV1 } from './models/PolicyPropertiesV1.ts';
export type { PostComputerPrestageV2 } from './models/PostComputerPrestageV2.ts';
export type { PrestageDependencies } from './models/PrestageDependencies.ts';
export type { PrestageDependency } from './models/PrestageDependency.ts';
export type { PrestageFileAttachment } from './models/PrestageFileAttachment.ts';
export type { PrestageFileAttachmentV2 } from './models/PrestageFileAttachmentV2.ts';
export type { PrestagePurchasingInformation } from './models/PrestagePurchasingInformation.ts';
export type { PrestagePurchasingInformationV2 } from './models/PrestagePurchasingInformationV2.ts';
export type { PrestageScope } from './models/PrestageScope.ts';
export type { PrestageScopeAssignment } from './models/PrestageScopeAssignment.ts';
export type { PrestageScopeAssignmentV2 } from './models/PrestageScopeAssignmentV2.ts';
export type { PrestageScopeResponse } from './models/PrestageScopeResponse.ts';
export type { PrestageScopeResponseV2 } from './models/PrestageScopeResponseV2.ts';
export type { PrestageScopeUpdate } from './models/PrestageScopeUpdate.ts';
export type { PrestageScopeV2 } from './models/PrestageScopeV2.ts';
export type { PrestageSyncStatus } from './models/PrestageSyncStatus.ts';
export type { PrestageSyncStatusV2 } from './models/PrestageSyncStatusV2.ts';
export type { ProcessTextsSearchResults } from './models/ProcessTextsSearchResults.ts';
export type { ProtectRegistrationRequest } from './models/ProtectRegistrationRequest.ts';
export type { ProtectSettingsResponse } from './models/ProtectSettingsResponse.ts';
export type { ProtectUpdatableSettingsRequest } from './models/ProtectUpdatableSettingsRequest.ts';
export type { ProvisioningProfile } from './models/ProvisioningProfile.ts';
export type { Purchasing } from './models/Purchasing.ts';
export type { PurchasingV2 } from './models/PurchasingV2.ts';
export type { PutComputerPrestage } from './models/PutComputerPrestage.ts';
export type { PutComputerPrestageV2 } from './models/PutComputerPrestageV2.ts';
export type { PutMobileDevicePrestage } from './models/PutMobileDevicePrestage.ts';
export type { PutMobileDevicePrestageV2 } from './models/PutMobileDevicePrestageV2.ts';
export type { RecalculationResults } from './models/RecalculationResults.ts';
export type { Recipient } from './models/Recipient.ts';
export type { Recipients } from './models/Recipients.ts';
export type { RedeployJamfManagementFrameworkResponse } from './models/RedeployJamfManagementFrameworkResponse.ts';
export type { Reenrollment } from './models/Reenrollment.ts';
export type { RemoteAdministrationResponse } from './models/RemoteAdministrationResponse.ts';
export type { RemoteAdministrationSearchResults } from './models/RemoteAdministrationSearchResults.ts';
export type { RenewMdmProfileResponse } from './models/RenewMdmProfileResponse.ts';
export type { RestartDeviceCommand } from './models/RestartDeviceCommand.ts';
export type { RetryPatchPolicyParams } from './models/RetryPatchPolicyParams.ts';
export type { SafelistedApp } from './models/SafelistedApp.ts';
export type { Script } from './models/Script.ts';
export type { ScriptsSearchResults } from './models/ScriptsSearchResults.ts';
export type { SearchActivePatchHistoryParams } from './models/SearchActivePatchHistoryParams.ts';
export type { SearchPatchPolicyLogParams } from './models/SearchPatchPolicyLogParams.ts';
export type { Security } from './models/Security.ts';
export type { SecurityV2 } from './models/SecurityV2.ts';
export type { SelfServiceInstallSettings } from './models/SelfServiceInstallSettings.ts';
export type { SelfServiceInteractionSettings } from './models/SelfServiceInteractionSettings.ts';
export type { SelfServiceLoginSettings } from './models/SelfServiceLoginSettings.ts';
export type { SelfServiceSettings } from './models/SelfServiceSettings.ts';
export type { Session } from './models/Session.ts';
export type { SessionCandidateRequest } from './models/SessionCandidateRequest.ts';
export type { SessionDetails } from './models/SessionDetails.ts';
export type { SessionDetailsSearchResults } from './models/SessionDetailsSearchResults.ts';
export type { SessionStatus } from './models/SessionStatus.ts';
export type { SetRecoveryLockCommand } from './models/SetRecoveryLockCommand.ts';
export type { SettingsCommand } from './models/SettingsCommand.ts';
export type { SharedDeviceConfiguration } from './models/SharedDeviceConfiguration.ts';
export type { Signature } from './models/Signature.ts';
export type { Site } from './models/Site.ts';
export type { SmartSearchCriterion } from './models/SmartSearchCriterion.ts';
export type { SoftwareTitleConfiguration } from './models/SoftwareTitleConfiguration.ts';
export type { SoftwareTitlePatchPolicySummaries } from './models/SoftwareTitlePatchPolicySummaries.ts';
export type { SoftwareUpdateSettings } from './models/SoftwareUpdateSettings.ts';
export type { SsoKeystore } from './models/SsoKeystore.ts';
export type { SsoKeystoreCertParseResponse } from './models/SsoKeystoreCertParseResponse.ts';
export type { SsoKeystoreDetails } from './models/SsoKeystoreDetails.ts';
export type { SsoKeystoreParse } from './models/SsoKeystoreParse.ts';
export type { SsoKeystoreResponse } from './models/SsoKeystoreResponse.ts';
export type { SsoKeystoreResponseWithDetails } from './models/SsoKeystoreResponseWithDetails.ts';
export type { SsoKeystoreWithDetails } from './models/SsoKeystoreWithDetails.ts';
export type { SsoMetadataUrl } from './models/SsoMetadataUrl.ts';
export type { SsoSettings } from './models/SsoSettings.ts';
export type { StartupStatus } from './models/StartupStatus.ts';
export type { StaticUserGroup } from './models/StaticUserGroup.ts';
export type { SupervisionIdentity } from './models/SupervisionIdentity.ts';
export type { SupervisionIdentityCertificateUpload } from './models/SupervisionIdentityCertificateUpload.ts';
export type { SupervisionIdentityCreate } from './models/SupervisionIdentityCreate.ts';
export type { SupervisionIdentitySearchResults } from './models/SupervisionIdentitySearchResults.ts';
export type { SupervisionIdentityUpdate } from './models/SupervisionIdentityUpdate.ts';
export type { TeacherFeatures } from './models/TeacherFeatures.ts';
export type { TeacherSettingsRequest } from './models/TeacherSettingsRequest.ts';
export type { TeacherSettingsResponse } from './models/TeacherSettingsResponse.ts';
export type { TimeFrame } from './models/TimeFrame.ts';
export type { TimeZone } from './models/TimeZone.ts';
export type { TvOsDetails } from './models/TvOsDetails.ts';
export type { Udids } from './models/Udids.ts';
export type { UpdateAppleTv } from './models/UpdateAppleTv.ts';
export type { UpdateIos } from './models/UpdateIos.ts';
export type { UpdateIosV2 } from './models/UpdateIosV2.ts';
export type { UpdateMobileDevice } from './models/UpdateMobileDevice.ts';
export type { UpdateMobileDeviceV2 } from './models/UpdateMobileDeviceV2.ts';
export type { UpdateTvOs } from './models/UpdateTvOs.ts';
export type { UserMappings } from './models/UserMappings.ts';
export type { UserPreferencesJson } from './models/UserPreferencesJson.ts';
export type { UserTestAttributes } from './models/UserTestAttributes.ts';
export type { UserTestSearch } from './models/UserTestSearch.ts';
export type { UserTestSearchRequest } from './models/UserTestSearchRequest.ts';
export type { UserTestSearchResponse } from './models/UserTestSearchResponse.ts';
export type { V1Site } from './models/V1Site.ts';
export type { VenafiCaRecord } from './models/VenafiCaRecord.ts';
export type { VenafiPkiPayloadRecord } from './models/VenafiPkiPayloadRecord.ts';
export type { VenafiPkiPayloadRecordSearchResults } from './models/VenafiPkiPayloadRecordSearchResults.ts';
export type { VenafiServiceStatus } from './models/VenafiServiceStatus.ts';
export type { VerbosePackageDeploymentResponse } from './models/VerbosePackageDeploymentResponse.ts';
export type { VoiceRoamingSetting } from './models/VoiceRoamingSetting.ts';
export type { VolumePurchasingContent } from './models/VolumePurchasingContent.ts';
export type { VolumePurchasingLocation } from './models/VolumePurchasingLocation.ts';
export type { VolumePurchasingLocationListView } from './models/VolumePurchasingLocationListView.ts';
export type { VolumePurchasingLocationPatch } from './models/VolumePurchasingLocationPatch.ts';
export type { VolumePurchasingLocationPost } from './models/VolumePurchasingLocationPost.ts';
export type { VolumePurchasingLocations } from './models/VolumePurchasingLocations.ts';
export type { VolumePurchasingSubscription } from './models/VolumePurchasingSubscription.ts';
export type { VolumePurchasingSubscriptionBase } from './models/VolumePurchasingSubscriptionBase.ts';
export type { VolumePurchasingSubscriptions } from './models/VolumePurchasingSubscriptions.ts';
export type { VppAdminAccount } from './models/VppAdminAccount.ts';
export type { VppTokenSubscription } from './models/VppTokenSubscription.ts';
export type { WebLink } from './models/WebLink.ts';

export { AdvancedMobileDeviceSearchesService } from './services/AdvancedMobileDeviceSearchesService.ts';
export { AdvancedUserContentSearchesService } from './services/AdvancedUserContentSearchesService.ts';
export { ApiAuthenticationService } from './services/ApiAuthenticationService.ts';
export { AppDynamicsConfigurationPreviewService } from './services/AppDynamicsConfigurationPreviewService.ts';
export { AppRequestPreviewService } from './services/AppRequestPreviewService.ts';
export { AppStoreCountryCodesPreviewService } from './services/AppStoreCountryCodesPreviewService.ts';
export { BuildingsService } from './services/BuildingsService.ts';
export { CacheSettingsService } from './services/CacheSettingsService.ts';
export { CategoriesService } from './services/CategoriesService.ts';
export { CertificateAuthorityService } from './services/CertificateAuthorityService.ts';
export { ClassicLdapService } from './services/ClassicLdapService.ts';
export { ClientCheckInService } from './services/ClientCheckInService.ts';
export { CloudAzureService } from './services/CloudAzureService.ts';
export { CloudIdpService } from './services/CloudIdpService.ts';
export { CloudLdapService } from './services/CloudLdapService.ts';
export { ComputerGroupsService } from './services/ComputerGroupsService.ts';
export { ComputerInventoryService } from './services/ComputerInventoryService.ts';
export { ComputerInventoryCollectionSettingsService } from './services/ComputerInventoryCollectionSettingsService.ts';
export { ComputerPrestagesService } from './services/ComputerPrestagesService.ts';
export { ComputersPreviewService } from './services/ComputersPreviewService.ts';
export { ConditionalAccessService } from './services/ConditionalAccessService.ts';
export { CsaService } from './services/CsaService.ts';
export { DepartmentsService } from './services/DepartmentsService.ts';
export { DeviceCommunicationSettingsService } from './services/DeviceCommunicationSettingsService.ts';
export { DeviceEnrollmentsService } from './services/DeviceEnrollmentsService.ts';
export { DeviceEnrollmentsDevicesService } from './services/DeviceEnrollmentsDevicesService.ts';
export { EbooksService } from './services/EbooksService.ts';
export { EngageService } from './services/EngageService.ts';
export { EnrollmentService } from './services/EnrollmentService.ts';
export { EnrollmentCustomizationService } from './services/EnrollmentCustomizationService.ts';
export { EnrollmentCustomizationPreviewService } from './services/EnrollmentCustomizationPreviewService.ts';
export { IconService } from './services/IconService.ts';
export { InventoryInformationService } from './services/InventoryInformationService.ts';
export { InventoryPreloadService } from './services/InventoryPreloadService.ts';
export { JamfConnectService } from './services/JamfConnectService.ts';
export { JamfManagementFrameworkService } from './services/JamfManagementFrameworkService.ts';
export { JamfPackageService } from './services/JamfPackageService.ts';
export { JamfProInformationService } from './services/JamfProInformationService.ts';
export { JamfProInitializationService } from './services/JamfProInitializationService.ts';
export { JamfProInitializationPreviewService } from './services/JamfProInitializationPreviewService.ts';
export { JamfProNotificationsService } from './services/JamfProNotificationsService.ts';
export { JamfProNotificationsPreviewService } from './services/JamfProNotificationsPreviewService.ts';
export { JamfProServerUrlPreviewService } from './services/JamfProServerUrlPreviewService.ts';
export { JamfProtectService } from './services/JamfProtectService.ts';
export { JamfProUserAccountSettingsService } from './services/JamfProUserAccountSettingsService.ts';
export { JamfProUserAccountSettingsPreviewService } from './services/JamfProUserAccountSettingsPreviewService.ts';
export { JamfProVersionService } from './services/JamfProVersionService.ts';
export { LdapService } from './services/LdapService.ts';
export { LocalesPreviewService } from './services/LocalesPreviewService.ts';
export { MacosManagedSoftwareUpdatesService } from './services/MacosManagedSoftwareUpdatesService.ts';
export { MdmService } from './services/MdmService.ts';
export { MobileDeviceEnrollmentProfileService } from './services/MobileDeviceEnrollmentProfileService.ts';
export { MobileDeviceExtensionAttributesPreviewService } from './services/MobileDeviceExtensionAttributesPreviewService.ts';
export { MobileDeviceGroupsPreviewService } from './services/MobileDeviceGroupsPreviewService.ts';
export { MobileDevicePrestagesService } from './services/MobileDevicePrestagesService.ts';
export { MobileDevicesService } from './services/MobileDevicesService.ts';
export { ParentAppPreviewService } from './services/ParentAppPreviewService.ts';
export { PatchesService } from './services/PatchesService.ts';
export { PatchesPreviewService } from './services/PatchesPreviewService.ts';
export { PatchPoliciesPreviewService } from './services/PatchPoliciesPreviewService.ts';
export { PatchPolicyLogsPreviewService } from './services/PatchPolicyLogsPreviewService.ts';
export { PoliciesPreviewService } from './services/PoliciesPreviewService.ts';
export { ReEnrollmentPreviewService } from './services/ReEnrollmentPreviewService.ts';
export { RemoteAdministrationService } from './services/RemoteAdministrationService.ts';
export { ScriptsService } from './services/ScriptsService.ts';
export { SelfServiceService } from './services/SelfServiceService.ts';
export { SelfServiceBrandingIosService } from './services/SelfServiceBrandingIosService.ts';
export { SelfServiceBrandingMacosService } from './services/SelfServiceBrandingMacosService.ts';
export { SelfServiceBrandingPreviewService } from './services/SelfServiceBrandingPreviewService.ts';
export { SitesService } from './services/SitesService.ts';
export { SitesPreviewService } from './services/SitesPreviewService.ts';
export { SmartComputerGroupsPreviewService } from './services/SmartComputerGroupsPreviewService.ts';
export { SmartMobileDeviceGroupsPreviewService } from './services/SmartMobileDeviceGroupsPreviewService.ts';
export { SmartUserGroupsPreviewService } from './services/SmartUserGroupsPreviewService.ts';
export { SsoCertificateService } from './services/SsoCertificateService.ts';
export { SsoCertificatePreviewService } from './services/SsoCertificatePreviewService.ts';
export { SsoSettingsService } from './services/SsoSettingsService.ts';
export { StartupStatusService } from './services/StartupStatusService.ts';
export { StaticUserGroupsPreviewService } from './services/StaticUserGroupsPreviewService.ts';
export { SupervisionIdentitiesPreviewService } from './services/SupervisionIdentitiesPreviewService.ts';
export { TeacherAppService } from './services/TeacherAppService.ts';
export { TeamViewerRemoteAdministrationService } from './services/TeamViewerRemoteAdministrationService.ts';
export { TimeZonesPreviewService } from './services/TimeZonesPreviewService.ts';
export { TomcatSettingsPreviewService } from './services/TomcatSettingsPreviewService.ts';
export { UserSessionPreviewService } from './services/UserSessionPreviewService.ts';
export { VenafiPreviewService } from './services/VenafiPreviewService.ts';
export { VolumePurchasingLocationsService } from './services/VolumePurchasingLocationsService.ts';
export { VolumePurchasingSubscriptionsService } from './services/VolumePurchasingSubscriptionsService.ts';
export { VppAdminAccountsPreviewService } from './services/VppAdminAccountsPreviewService.ts';
export { VppSubscriptionsPreviewService } from './services/VppSubscriptionsPreviewService.ts';
