/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
export { ApiError } from './core/ApiError.ts';
export { CancelablePromise, CancelError } from './core/CancelablePromise.ts';
export { OpenAPI } from './core/OpenAPI.ts';
export type { OpenAPIConfig } from './core/OpenAPI.ts';

export type { Account } from './models/Account.ts';
export type { ActivationCode } from './models/ActivationCode.ts';
export type { AdvancedComputerSearch } from './models/AdvancedComputerSearch.ts';
export type { AdvancedMobileDeviceSearch } from './models/AdvancedMobileDeviceSearch.ts';
export type { AdvancedUserSearch } from './models/AdvancedUserSearch.ts';
export type { AllowedFileExtension } from './models/AllowedFileExtension.ts';
export type { any } from './models/any.ts';
export type { Building } from './models/Building.ts';
export type { BYOProfile } from './models/BYOProfile.ts';
export type { Category } from './models/Category.ts';
export type { Class } from './models/Class.ts';
export type { commandflush } from './models/commandflush.ts';
export type { Computer } from './models/Computer.ts';
export type { ComputerApplications } from './models/ComputerApplications.ts';
export type { ComputerApplicationUsage } from './models/ComputerApplicationUsage.ts';
export type { ComputerCheckin } from './models/ComputerCheckin.ts';
export type { ComputerCommand } from './models/ComputerCommand.ts';
export type { ComputerConfiguration } from './models/ComputerConfiguration.ts';
export type { Computerextensionattribute } from './models/Computerextensionattribute.ts';
export type { ComputerGroup } from './models/ComputerGroup.ts';
export type { ComputerHardwareSoftwareReports } from './models/ComputerHardwareSoftwareReports.ts';
export type { ComputerHistory } from './models/ComputerHistory.ts';
export type { ComputerInventoryCollection } from './models/ComputerInventoryCollection.ts';
export type { ComputerInvitation } from './models/ComputerInvitation.ts';
export type { ComputerManagement } from './models/ComputerManagement.ts';
export type { Department } from './models/Department.ts';
export type { DirectoryBinding } from './models/DirectoryBinding.ts';
export type { Disk_Encryption_Configuration } from './models/Disk_Encryption_Configuration.ts';
export type { DistributionPoint } from './models/DistributionPoint.ts';
export type { DockItem } from './models/DockItem.ts';
export type { EBook } from './models/EBook.ts';
export type { FileUploads } from './models/FileUploads.ts';
export type { GSXConnection } from './models/GSXConnection.ts';
export type { HealthcareListener } from './models/HealthcareListener.ts';
export type { HealthcareListenerRule } from './models/HealthcareListenerRule.ts';
export type { IBeacon } from './models/IBeacon.ts';
export type { InfrastructureManager } from './models/InfrastructureManager.ts';
export type { JSON_Web_Token_Configuration } from './models/JSON_Web_Token_Configuration.ts';
export type { JSSUser } from './models/JSSUser.ts';
export type { LDAP_Server } from './models/LDAP_Server.ts';
export type { LicensedSoftware } from './models/LicensedSoftware.ts';
export type { logflush } from './models/logflush.ts';
export type { Macapp } from './models/Macapp.ts';
export type { ManagedPreferenceProfiles } from './models/ManagedPreferenceProfiles.ts';
export type { MobileDevice } from './models/MobileDevice.ts';
export type { MobileDeviceApplication } from './models/MobileDeviceApplication.ts';
export type { MobileDeviceCommand } from './models/MobileDeviceCommand.ts';
export type { MobileDeviceConfigurationProfile } from './models/MobileDeviceConfigurationProfile.ts';
export type { MobileDeviceEnrollmentProfile } from './models/MobileDeviceEnrollmentProfile.ts';
export type { Mobiledeviceextensionattribute } from './models/Mobiledeviceextensionattribute.ts';
export type { MobileDeviceGroup } from './models/MobileDeviceGroup.ts';
export type { MobileDeviceHistory } from './models/MobileDeviceHistory.ts';
export type { MobileDeviceInvitation } from './models/MobileDeviceInvitation.ts';
export type { MobileDeviceProvisioningProfile } from './models/MobileDeviceProvisioningProfile.ts';
export type { NetworkSegment } from './models/NetworkSegment.ts';
export type { OsxConfigurationProfile } from './models/OsxConfigurationProfile.ts';
export type { Package } from './models/Package.ts';
export type { Patch } from './models/Patch.ts';
export type { Patch_Available_Titles } from './models/Patch_Available_Titles.ts';
export type { Patch_External_Source } from './models/Patch_External_Source.ts';
export type { Patch_Internal_Source } from './models/Patch_Internal_Source.ts';
export type { Patch_Policy } from './models/Patch_Policy.ts';
export type { Peripheral } from './models/Peripheral.ts';
export type { Peripheral_Types } from './models/Peripheral_Types.ts';
export type { Policy } from './models/Policy.ts';
export type { Printer } from './models/Printer.ts';
export type { RemovableMacAddress } from './models/RemovableMacAddress.ts';
export type { RestrictedSoftware } from './models/RestrictedSoftware.ts';
export type { SavedSearch } from './models/SavedSearch.ts';
export type { Script } from './models/Script.ts';
export type { Site } from './models/Site.ts';
export type { SMTPServer } from './models/SMTPServer.ts';
export type { SoftwareUpdateServer } from './models/SoftwareUpdateServer.ts';
export type { User } from './models/User.ts';
export type { Userextensionattribute } from './models/Userextensionattribute.ts';
export type { UserGroup } from './models/UserGroup.ts';
export type { VPPAdminAccount } from './models/VPPAdminAccount.ts';
export type { VPPAssignment } from './models/VPPAssignment.ts';
export type { VPPInvitation } from './models/VPPInvitation.ts';
export type { Webhook } from './models/Webhook.ts';

export { AccountsService } from './services/AccountsService.ts';
export { ActivationcodeService } from './services/ActivationcodeService.ts';
export { AdvancedcomputersearchesService } from './services/AdvancedcomputersearchesService.ts';
export { AdvancedmobiledevicesearchesService } from './services/AdvancedmobiledevicesearchesService.ts';
export { AdvancedusersearchesService } from './services/AdvancedusersearchesService.ts';
export { AllowedfileextensionsService } from './services/AllowedfileextensionsService.ts';
export { BuildingsService } from './services/BuildingsService.ts';
export { ByoprofilesService } from './services/ByoprofilesService.ts';
export { CategoriesService } from './services/CategoriesService.ts';
export { ClassesService } from './services/ClassesService.ts';
export { CommandflushService } from './services/CommandflushService.ts';
export { ComputerapplicationsService } from './services/ComputerapplicationsService.ts';
export { ComputerapplicationusageService } from './services/ComputerapplicationusageService.ts';
export { ComputercheckinService } from './services/ComputercheckinService.ts';
export { ComputercommandsService } from './services/ComputercommandsService.ts';
export { ComputerextensionattributesService } from './services/ComputerextensionattributesService.ts';
export { ComputergroupsService } from './services/ComputergroupsService.ts';
export { ComputerhardwaresoftwarereportsService } from './services/ComputerhardwaresoftwarereportsService.ts';
export { ComputerhistoryService } from './services/ComputerhistoryService.ts';
export { ComputerinventorycollectionService } from './services/ComputerinventorycollectionService.ts';
export { ComputerinvitationsService } from './services/ComputerinvitationsService.ts';
export { ComputermanagementService } from './services/ComputermanagementService.ts';
export { ComputerreportsService } from './services/ComputerreportsService.ts';
export { ComputersService } from './services/ComputersService.ts';
export { DepartmentsService } from './services/DepartmentsService.ts';
export { DirectorybindingsService } from './services/DirectorybindingsService.ts';
export { DiskencryptionconfigurationsService } from './services/DiskencryptionconfigurationsService.ts';
export { DistributionpointsService } from './services/DistributionpointsService.ts';
export { DockitemsService } from './services/DockitemsService.ts';
export { EbooksService } from './services/EbooksService.ts';
export { FileuploadsService } from './services/FileuploadsService.ts';
export { GsxconnectionService } from './services/GsxconnectionService.ts';
export { HealthcarelistenerService } from './services/HealthcarelistenerService.ts';
export { HealthcarelistenerruleService } from './services/HealthcarelistenerruleService.ts';
export { IbeaconsService } from './services/IbeaconsService.ts';
export { InfrastructuremanagerService } from './services/InfrastructuremanagerService.ts';
export { JsonwebtokenconfigurationsService } from './services/JsonwebtokenconfigurationsService.ts';
export { JssuserService } from './services/JssuserService.ts';
export { LdapserversService } from './services/LdapserversService.ts';
export { LicensedsoftwareService } from './services/LicensedsoftwareService.ts';
export { LogflushService } from './services/LogflushService.ts';
export { MacapplicationsService } from './services/MacapplicationsService.ts';
export { ManagedpreferenceprofilesService } from './services/ManagedpreferenceprofilesService.ts';
export { MobiledeviceapplicationsService } from './services/MobiledeviceapplicationsService.ts';
export { MobiledevicecommandsService } from './services/MobiledevicecommandsService.ts';
export { MobiledeviceconfigurationprofilesService } from './services/MobiledeviceconfigurationprofilesService.ts';
export { MobiledeviceenrollmentprofilesService } from './services/MobiledeviceenrollmentprofilesService.ts';
export { MobiledeviceextensionattributesService } from './services/MobiledeviceextensionattributesService.ts';
export { MobiledevicegroupsService } from './services/MobiledevicegroupsService.ts';
export { MobiledevicehistoryService } from './services/MobiledevicehistoryService.ts';
export { MobiledeviceinvitationsService } from './services/MobiledeviceinvitationsService.ts';
export { MobiledeviceprovisioningprofilesService } from './services/MobiledeviceprovisioningprofilesService.ts';
export { MobiledevicesService } from './services/MobiledevicesService.ts';
export { NetworksegmentsService } from './services/NetworksegmentsService.ts';
export { OsxconfigurationprofilesService } from './services/OsxconfigurationprofilesService.ts';
export { PackagesService } from './services/PackagesService.ts';
export { PatchavailabletitlesService } from './services/PatchavailabletitlesService.ts';
export { PatchesService } from './services/PatchesService.ts';
export { PatchexternalsourcesService } from './services/PatchexternalsourcesService.ts';
export { PatchinternalsourcesService } from './services/PatchinternalsourcesService.ts';
export { PatchpoliciesService } from './services/PatchpoliciesService.ts';
export { PatchreportsService } from './services/PatchreportsService.ts';
export { PatchsoftwaretitlesService } from './services/PatchsoftwaretitlesService.ts';
export { PeripheralsService } from './services/PeripheralsService.ts';
export { PeripheraltypesService } from './services/PeripheraltypesService.ts';
export { PoliciesService } from './services/PoliciesService.ts';
export { PrintersService } from './services/PrintersService.ts';
export { RemovablemacaddressesService } from './services/RemovablemacaddressesService.ts';
export { RestrictedsoftwareService } from './services/RestrictedsoftwareService.ts';
export { SavedsearchesService } from './services/SavedsearchesService.ts';
export { ScriptsService } from './services/ScriptsService.ts';
export { SitesService } from './services/SitesService.ts';
export { SmtpserverService } from './services/SmtpserverService.ts';
export { SoftwareupdateserversService } from './services/SoftwareupdateserversService.ts';
export { UserextensionattributesService } from './services/UserextensionattributesService.ts';
export { UsergroupsService } from './services/UsergroupsService.ts';
export { UsersService } from './services/UsersService.ts';
export { VppaccountsService } from './services/VppaccountsService.ts';
export { VppassignmentsService } from './services/VppassignmentsService.ts';
export { VppinvitationsService } from './services/VppinvitationsService.ts';
export { WebhooksService } from './services/WebhooksService.ts';
